close all 
figure()
plot(out.Theta,'LineWidth',1.5)
xlabel('Time','interpreter','latex')
ylabel('$\theta$ response, $^\circ$','interpreter','latex')
title('Arm Angle','interpreter','latex')
figure()
plot(out.Tau,'LineWidth',1.5)
xlabel('Time','interpreter','latex')
ylabel('Torque, N-m','interpreter','latex')
title('Control Torque','interpreter','latex')
figure()
plot(out.Omega,'LineWidth',1.5)
xlabel('Time','interpreter','latex')
ylabel('Wheel velocity, $\frac{rad}{s}$','interpreter','latex')
title('Wheel Velocity','interpreter','latex')